# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 有个trash
subtitle: wut!人参早晚成trash,what kind of trash you would like to be?
avatar: https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwiV6NDtzNPiAhXDo1kKHQWYDv4QjRx6BAgBEAU&url=https%3A%2F%2Fcommunityimpact.com%2Fphoenix%2Fgilbert%2Fcity-county%2F2018%2F09%2F10%2Ftrash-pickup-days-in-gilbert-set-to-change-oct-1%2F&psig=AOvVaw3TPG5qvoXQcQaCMo8w6fR-&ust=1559867329894199
description: 我有祖传trash
author: trashman
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: 
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY年MM月D日  
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

server:
  port: 9000
  compress: true
  header: true


# Extensions
## Plugins: http://hexo.io/plugins/
plugins: hexo-generate-feed
